---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "AWS SAM cli install"
    init: |
      echo "Installing AWS SAM cli" # runs during prebuild
      wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      sudo ./sam-installation/install
      sam --version
      rm -rf sam-installation
      rm aws-sam-cli-linux-x86_64.zip
      gp sync-done SAM-install

  - name: "Pyenv install"
    init: |
      echo "Installing CLI"
      pyenv install 3.9-dev
      pyenv global 3.9-dev
      gp sync-done pyenv-install

# - name: "AWS SAM Build and Deploy"
#    init: |
#      echo "SAM build and deploy"
#      gp sync-await SAM-install
#      gp sync-await pyenv-install
#    command: |
#      sam build
#      sam deploy --stack-name $PY_LAMBDA_FN_STACK --resolve-s3

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
